/*
 * Game_UC.java
 *
 * Created on __DATE__, __TIME__
 */

package uc.panel;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.awt.event.MouseMotionListener;

import javax.swing.ImageIcon;
import javax.swing.JPanel;

import com.control.GameRunning;
import com.data.MImages;
import com.model.Bird;

import uc.button.*;
import form.*;
import resource.*;

/**
 *
 * @author  __USER__
 */
public class Game_UC extends MyPanel {

	/** Creates new form Game_UC */
	public Game_UC() {

		initComponents();

		this.setCursor(MImages.cursor_gm);

		this.menu_jButton.setVisible(false);
		//game = new GameRunning("/images/level1", this);
		game = new GameRunning(this);
	}

	public void selectLevel(String level) {

		int i = Integer.parseInt(level);
		this.setCursor(MImages.cursor_gm);
		game.createWorld(0);
		game.createModels(i);
		game.start();
	}

	public boolean nextLevel() {

		int level = game.level;
		if (level == MImages.levelNum)
			return false;

		game.createWorld(0);
		game.createModels(level + 1);
		game.start();
		return true;
	}

	GameRunning game;

	protected void cursorPressed(MouseEvent e) {

		//System.out.println(pressedX);
		this.setCursor(MImages.cursor_d);

	}

	protected void cursorReleased(MouseEvent e) {

		//System.out.println(pressedX);
		this.setCursor(MImages.cursor_gm);

	}

	public int getLevel() {
		return game.level;
	}

	public void gameFinish(boolean isWin, int score) {
		this.getMainForm().gameFinish(isWin, score);
	}

	//重新开始
	public void reStart() {
		//game.stop();
		game.init();

		//game.start();
		this.repaint();
	}

	public void gameCont() {
		game.gameContinue();
	}

	public void stop() {
		game.stop();
	}

	public void exit() {
		game.destory();
	}

	public void paint(Graphics g) {
		game.panitBefore(g);
		this.paintChildren(g);
		game.panitAfter(g);

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		pause_jButton = new MyButton(Images.BTN_PAUSE);
		start_jButton = new MyButton(Images.BTN_RESTARTG);
		menu_jButton = new MyButton(Images.BTN_MENU);
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		high_jLabel = new javax.swing.JLabel();
		score_jLabel = new javax.swing.JLabel();

		addComponentListener(new java.awt.event.ComponentAdapter() {
			public void componentShown(java.awt.event.ComponentEvent evt) {
				formComponentShown(evt);
			}
		});

		pause_jButton.setText("Pause");
		pause_jButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				pause_jButtonActionPerformed(evt);
			}
		});

		start_jButton.setText("Start");
		start_jButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				start_jButtonActionPerformed(evt);
			}
		});

		menu_jButton.setText("jButton3");

		jLabel1.setFont(new java.awt.Font("Highlight LET", 0, 35));
		jLabel1.setForeground(new java.awt.Color(102, 102, 102));
		jLabel1.setText("HIGHSCORE:");

		jLabel2.setFont(new java.awt.Font("Highlight LET", 0, 35));
		jLabel2.setForeground(new java.awt.Color(102, 102, 102));
		jLabel2.setText("SCORE:");

		high_jLabel.setFont(new java.awt.Font("Highlight LET", 0, 35));
		high_jLabel.setForeground(new java.awt.Color(102, 102, 102));
		high_jLabel.setText("jLabel3");

		score_jLabel.setFont(new java.awt.Font("Highlight LET", 0, 35));
		score_jLabel.setForeground(new java.awt.Color(102, 102, 102));
		score_jLabel.setText("jLabel4");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												pause_jButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												80,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												start_jButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												80,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(186, 186, 186)
										.addComponent(
												menu_jButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												80,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												445, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel1)
																		.addGap(
																				40,
																				40,
																				40)
																		.addComponent(
																				high_jLabel))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2)
																		.addGap(
																				39,
																				39,
																				39)
																		.addComponent(
																				score_jLabel)))
										.addGap(40, 40, 40)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								pause_jButton,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								80,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								start_jButton,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								80,
																								Short.MAX_VALUE))
																		.addContainerGap(
																				626,
																				Short.MAX_VALUE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				21,
																				21,
																				21)
																		.addComponent(
																				menu_jButton,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				80,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addContainerGap(
																				605,
																				Short.MAX_VALUE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								high_jLabel)
																						.addComponent(
																								jLabel1))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								score_jLabel)
																						.addComponent(
																								jLabel2))
																		.addContainerGap(
																				616,
																				Short.MAX_VALUE)))));
	}// </editor-fold>
	//GEN-END:initComponents

	private void start_jButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.reStart();
	}

	private void formComponentShown(java.awt.event.ComponentEvent evt) {
		// TODO add your handling code here:
		System.out.println("show" + this.getWidth());
	}

	private void pause_jButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		//Menu_Form jFrame = (Menu_Form) this.getParent().getParent();
		/*
		Pause_UC jPause = new Pause_UC();
		jPause.setBounds(0, 0, this.getWidth(), this.getHeight());
		this.add(jPause);
		
		this.setEnabled(false);
		this.validate();
		this.repaint();
		 */

		this.getMainForm().gamePuase();
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	public javax.swing.JLabel high_jLabel;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	public javax.swing.JButton menu_jButton;
	public javax.swing.JButton pause_jButton;
	public javax.swing.JLabel score_jLabel;
	public javax.swing.JButton start_jButton;
	// End of variables declaration//GEN-END:variables

}