/*
 * Menu_UC.java
 *
 * Created on __DATE__, __TIME__
 */

package uc.panel;

import java.awt.*;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URL;

import javax.imageio.ImageIO;
import javax.swing.*;

import com.data.MImages;

import uc.button.*;
import resource.*;

/**
 *
 * @author  __USER__
 */
public class Menu_UC extends MyPanel {

	/** Creates new form Menu_UC */
	public Menu_UC() {
		initComponents();
		//ImageIcon icon = new ImageIcon("/images/BUTTONS_SHEET_10.png");
		
	}
	
	protected void paintComponent(Graphics g) {
		//java.net.URL imageURL = getClass().getResource("/images/background3.png");
		Image image = null;
		ImageIcon icon = new ImageIcon(MImages.getPath() + "/data/images/background3.png");
		image = icon.getImage();
		/*
		try {
			image = ImageIO.read(imageURL);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}*/
		//image = image.getScaledInstance(this.getWidth(),this.getHeight(), Image.SCALE_SMOOTH);
		g.drawImage(image, 0, 0, this.getWidth(), this.getHeight(), this);

	
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		quit_jButton = new MyButton(Images.BTN_QUIT);
		startGame_jButton = new MyButton(Images.BTN_START);
		myLabel_11 = new uc.label.MyLabel_1();

		quit_jButton.setText(resource.TextString.BTN_QUIT);

		startGame_jButton.setText("Play Game");

		myLabel_11.setText("myLabel_11");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				quit_jButton,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				80,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				376,
																				376,
																				376)
																		.addComponent(
																				myLabel_11,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				501,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				442,
																				442,
																				442)
																		.addComponent(
																				startGame_jButton,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				340,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(403, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addGap(114, 114, 114)
										.addComponent(
												myLabel_11,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												136,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(62, 62, 62)
										.addComponent(
												startGame_jButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												194,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												163, Short.MAX_VALUE)
										.addComponent(
												quit_jButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												80,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private uc.label.MyLabel_1 myLabel_11;
	public javax.swing.JButton quit_jButton;
	public javax.swing.JButton startGame_jButton;
	// End of variables declaration//GEN-END:variables

}