/*
 * Pause_UC.java
 *
 * Created on __DATE__, __TIME__
 */

package uc.panel;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.MouseEvent;

import javax.swing.ImageIcon;

import com.data.MImages;

import resource.*;
import uc.button.*;

/**
 *
 * @author  __USER__
 */
public class Pause_UC extends MyPanel {

	/** Creates new form Pause_UC */
	public Pause_UC() {
		initComponents();
	}

	protected void paintComponent(Graphics g) {
		//java.net.URL imageURL = getClass().getResource("/images/pause.png");
		ImageIcon icon = new ImageIcon(MImages.getPath() + "/data/images/pause.png");
		g.drawImage(icon.getImage(), 0, 0, this.getWidth(), this.getHeight(),
				this);

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		reStart_jButton = new MyButton(Images.BTN_RESTART);
		cont_jButton = new MyButton(Images.BTN_CONTINUE);
		menu_jButton = new MyButton(Images.BTN_MENU);
		back_jButton = new MyButton(Images.BTN_SLEVEL);

		reStart_jButton.setText("ReStart");
		reStart_jButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				reStart_jButtonActionPerformed(evt);
			}
		});

		cont_jButton.setText("Continue");
		cont_jButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cont_jButtonActionPerformed(evt);
			}
		});

		menu_jButton.setText("Menu");
		menu_jButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				menu_jButtonActionPerformed(evt);
			}
		});

		back_jButton.setText("Level");
		back_jButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				back_jButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																menu_jButton,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																80,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																						.addComponent(
																								back_jButton,
																								0,
																								80,
																								Short.MAX_VALUE)
																						.addComponent(
																								reStart_jButton,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								80,
																								Short.MAX_VALUE))
																		.addGap(
																				31,
																				31,
																				31)
																		.addComponent(
																				cont_jButton,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				60,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(1126, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												reStart_jButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												80,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(54, 54, 54)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																back_jButton,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																80,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																cont_jButton,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																60,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(70, 70, 70)
										.addComponent(
												menu_jButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												80,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(342, Short.MAX_VALUE)));
	}// </editor-fold>
	//GEN-END:initComponents

	private void cont_jButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.getMainForm().pauseCont(this);
	}

	private void menu_jButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.getMainForm().pauseMenu(this);

	}

	private void back_jButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.getMainForm().returnSelectLevel(this);
	}

	private void reStart_jButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.getMainForm().gameReStart(this);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	public javax.swing.JButton back_jButton;
	public javax.swing.JButton cont_jButton;
	public javax.swing.JButton menu_jButton;
	public javax.swing.JButton reStart_jButton;
	// End of variables declaration//GEN-END:variables

}