/*
 * SelectLevel_UC.java
 *
 * Created on __DATE__, __TIME__
 */

package uc.panel;

import java.awt.*;
import java.awt.event.MouseEvent;

import javax.swing.*;

import com.data.MImages;

import uc.button.*;
import resource.*;

/**
 *
 * @author  __USER__
 */
public class SelectLevel_UC extends MyPanel {

	/** Creates new form SelectLevel_UC */
	public SelectLevel_UC() {
		initComponents();

	}

	public void paint(Graphics g) {
		//java.net.URL imageURL = getClass().getResource(
		//	"/images/BACKGROUNDS_LS_3.png");
		///ImageIcon icon = new ImageIcon(imageURL);
		//g.drawImage(icon.getImage(), 0, 0, this.getWidth(), this.getHeight(),
		//	this);

		g.drawImage(MImages.BACKGROUNDS_LS_3, 0, 0, this.getWidth(), this
				.getHeight(), this);
		//imageURL = getClass().getResource("/images/BACKGROUNDS_LS_2.png");
		//icon = new ImageIcon(imageURL);
		//g.drawImage(icon.getImage(), 0, 0, this.getWidth(), this.getHeight(),
		//this);
		g.drawImage(MImages.BACKGROUNDS_LS_2, 0, 0, this.getWidth(), this
				.getHeight(), this);

		this.paintChildren(g);

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		myLabel_21 = new uc.label.MyLabel_2();
		jLevel1Button = new LevelBtn(1);
		jPanel1 = new ImageItem_Panel(Images.LAB_LEVEL_LEFT);
		back_jButton = new MyButton(Images.BTN_BACK);
		myLabel_31 = new uc.label.MyLabel_3();
		jLevel2Button = new LevelBtn(2);
		jLevel3Button = new LevelBtn(3);
		jButton1 = new LevelBtn(4);
		jButton2 = new LevelBtn(5);
		jButton3 = new LevelBtn(6);
		jButton4 = new LevelBtn(7);
		jButton5 = new LevelBtn(8);
		jButton6 = new LevelBtn(9);
		jButton7 = new LevelBtn(10);

		myLabel_21.setText("myLabel_21");

		jLevel1Button.setText("1");
		jLevel1Button.setName("1");

		back_jButton.setText("jButton2");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addComponent(
						back_jButton, javax.swing.GroupLayout.PREFERRED_SIZE,
						80, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(100, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel1Layout.createSequentialGroup().addContainerGap(100,
						Short.MAX_VALUE).addComponent(back_jButton,
						javax.swing.GroupLayout.PREFERRED_SIZE, 80,
						javax.swing.GroupLayout.PREFERRED_SIZE)));

		myLabel_31.setText("myLabel_31");

		jLevel2Button.setText("jButton1");
		jLevel2Button.setName("2");

		jLevel3Button.setText("jButton1");
		jLevel3Button.setName("3");

		jButton1.setText("jButton1");
		jButton1.setName("4");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("jButton2");
		jButton2.setName("5");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton3.setText("jButton3");
		jButton3.setName("6");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton4.setText("jButton4");
		jButton4.setName("7");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton5.setText("jButton5");
		jButton5.setName("8");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton6.setText("jButton6");
		jButton6.setName("9");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton7.setText("jButton7");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(
												jPanel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												996, Short.MAX_VALUE)
										.addComponent(
												myLabel_31,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												180,
												javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(
								layout.createSequentialGroup().addGap(372, 372,
										372).addComponent(myLabel_21,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										490,
										javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(494, Short.MAX_VALUE))
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(279, 279, 279)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLevel1Button,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				80,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				70,
																				70,
																				70)
																		.addComponent(
																				jLevel2Button,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				80,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				58,
																				58,
																				58)
																		.addComponent(
																				jLevel3Button,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				80,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				64,
																				64,
																				64)
																		.addComponent(
																				jButton1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				80,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton3)
																		.addGap(
																				69,
																				69,
																				69)
																		.addComponent(
																				jButton4)
																		.addGap(
																				57,
																				57,
																				57)
																		.addComponent(
																				jButton5)
																		.addGap(
																				63,
																				63,
																				63)
																		.addComponent(
																				jButton6)))
										.addGap(64, 64, 64)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jButton2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																80,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton7,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap(419, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addGap(104, 104, 104)
										.addComponent(
												myLabel_21,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												109,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												78, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jLevel1Button,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jLevel2Button,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				100,
																				Short.MAX_VALUE)
																		.addComponent(
																				jLevel3Button,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				100,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButton1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				100,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jButton2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				100,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jButton3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								100,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton4,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								100,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton5,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								100,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton6,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								100,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				50,
																				50,
																				50)
																		.addComponent(
																				myLabel_31,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				180,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(
																jButton7,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																100,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addGap(549, 549,
										549).addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)));
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.getMainForm().levelSelect(evt);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	public javax.swing.JButton back_jButton;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	public javax.swing.JButton jLevel1Button;
	public javax.swing.JButton jLevel2Button;
	public javax.swing.JButton jLevel3Button;
	private javax.swing.JPanel jPanel1;
	private uc.label.MyLabel_2 myLabel_21;
	private uc.label.MyLabel_3 myLabel_31;
	// End of variables declaration//GEN-END:variables

}