/*
 * Success_UC.java
 *
 * Created on __DATE__, __TIME__
 */

package uc.panel;

import java.awt.Graphics;
import java.awt.Image;

import javax.swing.ImageIcon;

import com.data.MImages;

import resource.*;
import uc.button.*;

/**
 *
 * @author  __USER__
 */
public class Success_UC extends MyPanel {

	/** Creates new form Success_UC */
	public Success_UC() {
		initComponents();

	}

	Image img = null;
	boolean isNewHighScore = false;

	public void win(boolean isWin, int level, int score) {
		this.jButton3.setVisible(false);
		img = null;
		if (level < MImages.levelNum) {
			this.jButton3.setVisible(true);
		}
		if (isWin) {

			this.win_jLabel.setText("WIN");
			if (score > MImages.levelList[level - 1].highScore) {
				MImages.levelList[level - 1].highScore = score;
				MImages.updateHighScore(level);
				img = MImages.newScore;
			}

		} else {
			this.win_jLabel.setText("FAIL");
		}
		//img = MImages.newScore;
		this.high_jLabel.setText("" + MImages.levelList[level - 1].highScore);
		this.score_jLabel.setText("" + score);
		this.getMainForm().main_jPanel.repaint();
	}

	protected void paintComponent(Graphics g) {

		//java.net.URL imageURL = getClass().getResource("/images/success.png");
		ImageIcon icon = new ImageIcon(MImages.getPath()
				+ "/data/images/success.png");
		g.drawImage(icon.getImage(), 0, 0, this.getWidth(), this.getHeight(),
				this);
		if (img != null) {
			g.drawImage(img, 650, 290, this);
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jButton1 = new MyButton(Images.BTN_SLEVEL);
		jButton2 = new MyButton(Images.BTN_RESTART);
		jButton3 = new MyButton(Images.BTN_NEXT);
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		score_jLabel = new javax.swing.JLabel();
		win_jLabel = new javax.swing.JLabel();
		high_jLabel = new javax.swing.JLabel();

		jButton1.setText("Level");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("ReStart");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("Next");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Highlight LET", 0, 25));
		jLabel1.setText("Score:");

		jLabel2.setFont(new java.awt.Font("Highlight LET", 0, 30));
		jLabel2.setText("High Score:");

		score_jLabel.setFont(new java.awt.Font("Highlight LET", 0, 25));
		score_jLabel.setText("jLabel3");

		win_jLabel.setFont(new java.awt.Font("Highlight LET", 0, 35));
		win_jLabel.setText("jLabel3");

		high_jLabel.setFont(new java.awt.Font("Highlight LET", 0, 20));
		high_jLabel.setText("jLabel3");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(421, 421, 421)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGap(
																												15,
																												15,
																												15)
																										.addComponent(
																												win_jLabel))
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jButton1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												80,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(
																												53,
																												53,
																												53)
																										.addComponent(
																												jButton2,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												80,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(
																												50,
																												50,
																												50)
																										.addComponent(
																												jButton3,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												80,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel1)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												score_jLabel)))
																		.addGap(
																				36,
																				36,
																				36))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				223,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel2,
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												high_jLabel)
																										.addGap(
																												68,
																												68,
																												68)))))
										.addContainerGap(493, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(166, 166, 166)
										.addComponent(jLabel2)
										.addGap(12, 12, 12)
										.addComponent(high_jLabel)
										.addGap(64, 64, 64)
										.addComponent(win_jLabel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																score_jLabel,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																29,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(17, 17, 17)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jButton1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																80,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																80,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																80,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(218, Short.MAX_VALUE)));
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.getMainForm().nextLevel(this);
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.getMainForm().gameReStart(this);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.getMainForm().returnSelectLevel(this);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel high_jLabel;
	public javax.swing.JButton jButton1;
	public javax.swing.JButton jButton2;
	public javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel score_jLabel;
	private javax.swing.JLabel win_jLabel;
	// End of variables declaration//GEN-END:variables

}